[package]
name = "gpsami"
version = "0.1.0"
authors = ["Hubert Figui√®re <hub@figuiere.net>"]
license = "GPL-3"

[dependencies]
glib-sys = "0.3.2"
gobject-sys = "0.3.2"
gio-sys = "0.3.2"
glib = { version="0.1.1", features = ["v2_40"] }
gio = { version="0.1.1", features = ["v2_40"] }
gtk = { version="0.1.1", features = ["v3_12"] }
rustc-serialize = "0.3"
libudev = "0.2.0"
gudev = { version="0.1.1", git="https://github.com/hfiguiere/gudev-rs" }

[[bin]]
name = "gpsami"
